sonar.projectKey=skybooker-frontend
sonar.projectName=SkyBooker Frontend
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

# Source folders
sonar.sources=src

# Test files
sonar.tests=src

# Include spec files
sonar.test.inclusions=**/*.spec.ts

# Exclude unnecessary files
sonar.exclusions=**/node_modules/**,**/*.spec.ts

# TypeScript coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Angular / TS
sonar.typescript.tsconfigPath=tsconfig.json